# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_module/proto/config.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n config_module/proto/config.proto\x12\x06\x63onfig\"\x1f\n\rConfigRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\"4\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"4\n\x0b\x43onfigReply\x12%\n\x0b\x63onfig_data\x18\x01 \x03(\x0b\x32\x10.config.KeyValue2I\n\x0c\x43onfigServer\x12\x39\n\tGetConfig\x12\x15.config.ConfigRequest\x1a\x13.config.ConfigReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_module.proto.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGREQUEST']._serialized_start=44
  _globals['_CONFIGREQUEST']._serialized_end=75
  _globals['_KEYVALUE']._serialized_start=77
  _globals['_KEYVALUE']._serialized_end=129
  _globals['_CONFIGREPLY']._serialized_start=131
  _globals['_CONFIGREPLY']._serialized_end=183
  _globals['_CONFIGSERVER']._serialized_start=185
  _globals['_CONFIGSERVER']._serialized_end=258
# @@protoc_insertion_point(module_scope)
